### ISSUE TITLE
Link to `rust-style` is dead

### ISSUE THREAD

**Issue by ntrepid8** [kylepink/RustCodeFormatter#3]
The links to `rust-style` seem to be dead.  I just get a github 404 page when I go to this page:

https://github.com/sp0/rust-style

**Comment by kylepink** [comment]
Looks like rust-style has been deleted, unfortunately this plugin is now useless.
I will remove this plugin from package control channel for now.

When I get around to it I may modify this project to use (which is more advanced and better supported):
https://github.com/nrc/rustfmt

**Comment by ntrepid8** [comment]
:+1:
